name: Release Schema
on:
  push:
    tags:
      - "v*" # 触发：以 v 开头的标签，如 v1.0.0
  workflow_dispatch: # 手动触发工作流

concurrency:
  group: release-standard
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Extract tag version
        id: extract_tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
          echo "RELEASE_TITLE=${TAG_VERSION} Rime万象拼音输入方案，全新词库，全新语法模型" >> $GITHUB_ENV

      - name: Release build
        run: bash .github/workflows/scripts/release-build.sh

      - name: Generate changelog from commits
        shell: bash
        run: |
          echo "### ${RELEASE_HEADER}" > release_notes.md
          echo "---" >> release_notes.md
          echo "" >> release_notes.md
          echo "#### 1. 标准版输入方案" >> release_notes.md
          echo "✨**适用类型：** 支持全拼、各种双拼" >> release_notes.md
          echo "✨**下载地址：** [rime-wanxiang-base.zip](https://github.com/${{ github.repository }}/releases/download/${TAG_VERSION}/rime-wanxiang-base.zip)" >> release_notes.md
          echo "" >> release_notes.md
          echo "#### 2. 双拼辅助码增强版输入方案" >> release_notes.md
          echo "✨**适用类型：** 支持各种双拼+辅助码的自由组合" >> release_notes.md

          declare -A display_names=(
            [zrm]="自然码"
            [moqi]="墨奇"
            [flypy]="小鹤"
            [jdh]="简单鹤"
            [hanxin]="汉心"
            [wubi]="五笔前2"
            [tiger]="虎码首末"
          )

          for type in zrm moqi flypy jdh hanxin wubi tiger; do
            name="${display_names[$type]}"
            echo "- **${name}辅助版本：** [rime-wanxiang-${type}-fuzhu.zip](https://github.com/${{ github.repository }}/releases/download/${TAG_VERSION}/rime-wanxiang-${type}-fuzhu.zip)" >> release_notes.md
          done

          echo "" >> release_notes.md
          echo "#### 3. 语法模型" >> release_notes.md
          echo "✨**适用类型：** 所有版本皆可用" >> release_notes.md
          echo "✨**下载地址：** [wanxiang-lts-zh-hans.gram](https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hans.gram)" >> release_notes.md
          echo "" >> release_notes.md
          echo "#### 📝 更新日志" >> release_notes.md
          git log --pretty=format:"- %s (%an)" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> release_notes.md
          echo "" >> release_notes.md
          echo "---" >> release_notes.md
          echo "#### 📘 使用说明" >> release_notes.md
          echo "" >> release_notes.md
          echo "1. **不使用辅助码的用户** 请直接下载标准版，按仓库中的 [README.md](https://github.com/${{ github.repository }}/blob/main/README.md) 配置使用。" >> release_notes.md
          echo "" >> release_notes.md
          echo "2. **使用增强版的用户：**" >> release_notes.md
          echo "   - PRO 每一个 zip 是**完整独立配置包**，其差异仅在于词库是否带有特定辅助码。" >> release_notes.md
          echo "   - flypy 仅表示“词库中包含小鹤辅助码”，并**不代表这是小鹤双拼方案**。" >> release_notes.md
          echo "   - 万象输入法可任意组合任意双拼与任意辅助码，请根据需要选择对应包。" >> release_notes.md
          echo "   - 想要**携带全部辅助码**？直接克隆仓库即可。" >> release_notes.md
          echo "   - 若已有目标辅助码类型，只需下载对应 zip，解压后根据 README 中提示修改表头（例如双拼方案）即可使用。" >> release_notes.md
          echo "" >> release_notes.md
          echo "3. **语法模型需单独下载**，并放入输入法用户目录根目录（与方案文件放一起），**无需配置**。" >> release_notes.md
          echo "" >> release_notes.md
          echo "4. 💾 飞机盘下载地址（最快更新）：[点击访问](https://share.feijipan.com/s/xiGvXdKz)" >> release_notes.md
          echo "5. 🛠 推荐使用更新脚本优雅管理版本：[rime-wanxiang-weasel-update-tools](https://github.com/expoli/rime-wanxiang-weasel-update-tools)" >> release_notes.md

      - name: Create Release and Upload
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELEASE_TITLE }} #发布页标题
          tag_name: ${{ github.ref_name }}
          files: |
            dist/rime-wanxiang-*.zip
          body_path: release_notes.md
          draft: ${{ github.event_name == 'workflow_dispatch' }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
