name: Release Schema
on:
  push:
    tags:
      - "v*" # 触发：以 v 开头的标签，如 v1.0.0
  workflow_dispatch: # 手动触发工作流

concurrency:
  group: release-standard
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Extract tag version
        id: extract_tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
          echo "RELEASE_TITLE=${TAG_VERSION} Rime万象拼音输入方案，全新词库，全新语法模型" >> $GITHUB_ENV

      - name: Release build
        run: bash .github/workflows/scripts/release-build.sh

      - name: Generate changelog from commits
        run: bash .github/workflows/scripts/generate-release-note.sh

      - name: Create Release and Upload
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELEASE_TITLE }} #发布页标题
          tag_name: ${{ github.ref_name }}
          files: |
            dist/rime-wanxiang-*.zip
          body_path: release_notes.md
          draft: ${{ github.event_name == 'workflow_dispatch' }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
